name: Build

on:
    push:
        paths:
            - "src/**"

jobs:
    server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: yarn && yarn build
